
// export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGGEDIN = 'USER_LOGGEDIN';
export const LOGIN_ERRORS = 'LOGIN_ERRORS';
export const USER_PROFILE = 'USER_PROFILE';
export const USER_SIGNUP = 'USER_SIGNUP';
export const REQUEST_SIGNUP = 'REQUEST_SIGNUP';
export const REQUEST_EDIT_PROFILE = 'REQUEST_EDIT_PROFILE';
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const CHANGE_PASSWORD_ERROR = 'PASSWORD_ERROR';
export const SIGNUP_ERRORS = 'SIGNUP_ERRORS';
export const GET_PROFILE ='GET_PROFILE';
export const GET_FRIENDS='GET_FRIENDS';
export const GET_BALANCE='GET_FRIENDS';
export const GET_RECENT_TRANSACTION='GET_RECENT_TRANSACTION';


